version: "3.7"
services:

  #PHP Service
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: deliverit
    container_name: deliverit-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - deliverit

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: deliverit-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: corrida-deliverit
      MYSQL_ROOT_PASSWORD: corrida-deliverit
      MYSQL_PASSWORD: corrida-deliverit
      MYSQL_USER: corrida-deliverit
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/:/docker-entrypoint-initdb.d/
    networks:
      - deliverit

  #Nginx Service
  nginx:
    image: nginx:1.17-alpine
    container_name: deliverit-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - deliverit

networks:
  deliverit:
    driver: bridge
